### ISSUE TITLE
TLS errors when installing pg 8

### ISSUE THREAD

**Issue by danielleadams** [heroku/node-js-getting-started#166]
When installing the `pg` package latest version, the following happens when accessing the `/db` endpoint:

```
2020-04-01T21:04:18.128008+00:00 app[web.1]: Error: self signed certificate
2020-04-01T21:04:18.128018+00:00 app[web.1]: at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
2020-04-01T21:04:18.128020+00:00 app[web.1]: at TLSSocket.emit (events.js:311:20)
2020-04-01T21:04:18.128020+00:00 app[web.1]: at TLSSocket._finishInit (_tls_wrap.js:916:8)
2020-04-01T21:04:18.128021+00:00 app[web.1]: at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
2020-04-01T21:04:18.128021+00:00 app[web.1]: code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
2020-04-01T21:04:18.128022+00:00 app[web.1]: }
```

Using `pg < 8` is a temporary workaround.

**Comment by danielleadams** [comment]
Fixed when specifying at connection to `rejectUnauthorized: false`.
