### ISSUE TITLE
  response.redirect is not a function || response.sendfile is not a function

### ISSUE THREAD

**Issue by SudhirKaushik** [heroku/node-js-getting-started#96]
I created nodejs app on heroku. On local, everything works fine, but in heroku logs I got this: 

`2018-01-05T12:03:54.148483+00:00 app[api]: Release v44 created by user shudhpandit1@gmail.com
2018-01-05T12:03:58.381790+00:00 app[web.1]: /appHello
2018-01-05T12:03:58.383453+00:00 app[web.1]: Server running at 26153
2018-01-05T12:03:58.930844+00:00 heroku[web.1]: State changed from starting to up
2018-01-05T12:04:18.574589+00:00 heroku[router]: at=info method=GET path="/" host=hidden-citadel-39641.herokuapp.com request_id=fc47fbb7-bdac-48e5-
81d6-1fd87c946f22 fwd="106.223.191.132" dyno=web.1 connect=1ms service=11ms status=200 bytes=151 protocol=https
2018-01-05T12:04:18.577684+00:00 app[web.1]: /app/server.js:14
2018-01-05T12:04:18.577705+00:00 app[web.1]: response.redirect('http://google.com');
2018-01-05T12:04:18.577706+00:00 app[web.1]:          ^
2018-01-05T12:04:18.577707+00:00 app[web.1]:
2018-01-05T12:04:18.577708+00:00 app[web.1]: TypeError: response.redirect is not a function
2018-01-05T12:04:18.577709+00:00 app[web.1]:     at Server.<anonymous> (/app/server.js:14:10)
2018-01-05T12:04:18.577710+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2018-01-05T12:04:18.577712+00:00 app[web.1]:     at Server.emit (events.js:191:7)
2018-01-05T12:04:18.577714+00:00 app[web.1]:     at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:548:12)
2018-01-05T12:04:18.577715+00:00 app[web.1]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
2018-01-05T12:04:18.686158+00:00 heroku[web.1]: State changed from up to crashed
2018-01-05T12:04:18.670728+00:00 heroku[web.1]: Process exited with status 1`

Morever, I am getting error for 'response.sendfile is not a function' with small f and 'response.sendFile is not a function' with big F.

Package.json has:
`  "dependencies": {
    "body-parser": "~1.5.2",
    "express": "^4.8.0",
    "gulp-bower-fix-css-path": "^0.1.1",
    "gzippo": "^0.2.0",
    "method-override": "~2.1.2",`

Server.js has:

`//Load HTTP module
var express = require('express');
const app = express();
var http = require("http");
var port = process.env.PORT|| 8000 ;
//Create HTTP server and listen on port 8000 for requests
http.createServer(function (request, response) {

   // Set the response HTTP header with HTTP status and Content type
   response.writeHead(200, {'Content-Type': 'text/plain'});
   
   // Send the response body "Hello World"
   response.end('Hello World\n');
response.redirect('http://google.com');
     response.sendFile('./views/main.html');

}).listen(port);
// Catch all other routes and return the index file
app.use(express.static(__dirname + '/views'));

console.log(__dirname+"Hello");

app.get('*',function(req, res){
  res.sendfile(path.join(__dirname+'/index.html'));
});
// Print URL for accessing server
console.log('Server running at '+port);`

**Comment by jmorrell** [comment]
Please open a ticket at https://help.heroku.com/ when you encounter issues using Heroku

In this case it looks like you are confusing the request and response objects created by Express: http://expressjs.com/en/4x/api.html#res and the native request and response objects in Node: https://nodejs.org/api/http.html#http_class_http_serverresponse which doesn't have the methods you're trying to use.

You also send off the request with `response.end`, but then try to call further methods on it, which will not work. You cannot respond multiple times over HTTP, just once. This likely throws errors locally that you are not seeing for some reason.

I recommend starting with an Express guide and building off of that: http://expressjs.com/en/starter/basic-routing.html
